/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aut.utcluj.isp.ex3;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class EquipmentUI extends javax.swing.JFrame {

    /**
     * Creates new form EquipmentUI
     */
    public EquipmentUI() {
        initComponents();
    }

    
    EquipmentController EController = new EquipmentController();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        getButton = new javax.swing.JButton();
        getNoButton = new javax.swing.JButton();
        groupButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Add Equipment");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        getButton.setText("Get Equipments");
        getButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getButtonActionPerformed(evt);
            }
        });

        getNoButton.setText("Get No. of Equipments");
        getNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNoButtonActionPerformed(evt);
            }
        });

        groupButton.setText("Group Equipments");
        groupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remove Equipment");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        messageBox.setEditable(false);
        messageBox.setColumns(20);
        messageBox.setRows(5);
        jScrollPane1.setViewportView(messageBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeButton)
                    .addComponent(groupButton)
                    .addComponent(getNoButton)
                    .addComponent(getButton)
                    .addComponent(addButton))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(getButton)
                        .addGap(18, 18, 18)
                        .addComponent(getNoButton)
                        .addGap(18, 18, 18)
                        .addComponent(groupButton)
                        .addGap(18, 18, 18)
                        .addComponent(removeButton)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void getButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getButtonActionPerformed
        List<Equipment> equipmentList = new ArrayList<Equipment>();
        
        equipmentList = EController.getEquipments();
        
        String outputMessage = "Get Equipments:";
        
        for(Equipment e : equipmentList){
            outputMessage = outputMessage + "\n" + "Serial Number: " + e.getSerialNumber() + "; Name:" + e.getName() + "; Owner:" + e.getOwner();
        }
        
        messageBox.setText(outputMessage);
    }//GEN-LAST:event_getButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String serialNumber = JOptionPane.showInputDialog(this, "Enter Serial Number of the Equipment");
        String nameOfEquipment = JOptionPane.showInputDialog(this, "Enter the Name of the Equipment");
        String nameOfOwner = JOptionPane.showInputDialog(this, "Enter the Owner's Name of the Equipment");
        
        Equipment newEquipment = new Equipment(nameOfEquipment, serialNumber, nameOfOwner);
        
        String outputMessage = "Add Equipment:";
        
        if(serialNumber.equals("")){
            outputMessage = outputMessage + "\n\n" + "Please insert a Serial Number";
        }
        else{
            if(EController.addEquipment(newEquipment)){
                outputMessage = outputMessage + "\n\n" +serialNumber+" is added";
            }
            else{
                outputMessage = outputMessage + "\n\n" + "This Equipment is already added";
            }
        }
        
        messageBox.setText(outputMessage);
    }//GEN-LAST:event_addButtonActionPerformed

    private void getNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNoButtonActionPerformed
        messageBox.setText("The Number of Equipments is: "+EController.getNumberOfEquipments());
    }//GEN-LAST:event_getNoButtonActionPerformed

    private void groupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupButtonActionPerformed
         Map<String, List<Equipment>> groupedList = EController.getEquipmentsGroupedByOwner();
         
         String outputMessage = "Grouped Equipments:\n";
         
         for (Map.Entry mapElement : groupedList.entrySet()) {
            String key = (String)mapElement.getKey();
            
            outputMessage = outputMessage + "\nFrom " + key + ":\n";
            
            List<Equipment> myList = (List)mapElement.getValue();

            for (Equipment elements: myList){
                outputMessage = outputMessage + "   Name:" + elements.getName() + "; Serial Number: "+elements.getSerialNumber() + ";\n";
            }
        }
         
        messageBox.setText(outputMessage);
    }//GEN-LAST:event_groupButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        String serialNumber = JOptionPane.showInputDialog(this, "Enter Serial Number of the Equipment");
        
        Equipment removedEqipment = EController.removeEquipmentBySerialNumber(serialNumber);
        
        messageBox.setText("Remove Equipment:\n");
        
        if(removedEqipment == null){
            messageBox.setText("The "+serialNumber+" is NOT found");
        }
        else{
            messageBox.setText("The "+serialNumber+" is removed");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EquipmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EquipmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EquipmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EquipmentUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EquipmentUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton getButton;
    private javax.swing.JButton getNoButton;
    private javax.swing.JButton groupButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageBox;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
